version: '3.9'

services:
    postgres:
        container_name: postgres-mirea
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - 5434:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - mountain-managment

volumes:
    postgres_data:

networks:
    mountain-managment:
