export const columnMappings = {
	id: 'Идентификатор',
	fullName: 'ФИО',
	address: 'Адрес',
	phoneNumber: 'Номер телефона',
	createdAt: 'Дата создания',
	updatedAt: 'Дата обновления',
	relationship: 'Связь',
	name: 'Название',
	climbers: 'Альпинист',
	startDate: 'Дата начала восхождения',
	endDate: 'Дата окончания экспедиции',
	country: 'Страна',
	region: 'Регион',
	height: 'Высота (м)',
	firstName: 'Имя',
	lastName: 'Фамилия',
	email: 'Электронная почта',
	role: 'Роль',
};
